In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd
import numpy as np

In [4]:
dataset = pd.read_csv("dataset/DATA_copy_columndevided.csv")

In [5]:
X = dataset.iloc[:, 1:31].values
y = dataset.iloc[:, 32].values

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20)

In [9]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
classifier = DecisionTreeClassifier()
classifier.fit(X_train,y_train)

DecisionTreeClassifier()

In [11]:
y_predict = classifier.predict(X_test)

In [12]:
print(confusion_matrix(y_test,y_predict))
print(classification_report(y_test, y_predict))

[[0 0 1 2 0 0 0 0]
 [0 0 1 1 0 3 2 3]
 [0 1 0 0 1 0 0 0]
 [0 1 1 0 0 3 0 0]
 [0 0 0 0 0 0 2 1]
 [0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 1]
 [0 0 1 0 0 0 0 2]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.00      0.00      0.00        10
           2       0.00      0.00      0.00         2
           3       0.00      0.00      0.00         5
           4       0.00      0.00      0.00         3
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         2
           7       0.25      0.67      0.36         3

    accuracy                           0.07        29
   macro avg       0.03      0.08      0.05        29
weighted avg       0.03      0.07      0.04        29



C:\Users\nethm\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\nethm\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\nethm\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
